package model;
// Generated 22/09/2013 15:07:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Entrada generated by hbm2java
 */
public class Entrada  implements java.io.Serializable {


     private Long id;
     private Usuario usuario;
     private Empenho empenho;
     private String numeroNota;
     private Date data;
     private float valorTotal;
     private Set itensEntradas = new HashSet(0);
     static Entrada instancia = null;   
   
     
     public static Entrada getInstacia(){
       if(  instancia == null){
         return instancia = new Entrada();
         } else{ 
         return instancia;
       }
     }
     
     
    public Entrada() {
    }

	
    public Entrada(Usuario usuario, Empenho empenho, Date data, float valorTotal) {
        this.usuario = usuario;
        this.empenho = empenho;
        this.data = data;
        this.valorTotal = valorTotal;
    }
    public Entrada(Usuario usuario, Empenho empenho, String numeroNota, Date data, float valorTotal, Set itensEntradas) {
       this.usuario = usuario;
       this.empenho = empenho;
       this.numeroNota = numeroNota;
       this.data = data;
       this.valorTotal = valorTotal;
       this.itensEntradas = itensEntradas;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Empenho getEmpenho() {
        return this.empenho;
    }
    
    public void setEmpenho(Empenho empenho) {
        this.empenho = empenho;
    }
    public String getNumeroNota() {
        return this.numeroNota;
    }
    
    public void setNumeroNota(String numeroNota) {
        this.numeroNota = numeroNota;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public float getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }
    public Set getItensEntradas() {
        return this.itensEntradas;
    }
    
    public void setItensEntradas(Set itensEntradas) {
        this.itensEntradas = itensEntradas;
    }




}


