package model;
// Generated 22/09/2013 15:07:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Entrada generated by hbm2java
 */
public class Entrada  implements java.io.Serializable {


     private Long id;
     private Empenho empenho;
     private String numeroNota;
     private Date data;
     private float valorTotal;
     static Entrada instancia = null;   
   
     
     public static Entrada getInstacia(){
       if(  instancia == null){
         return instancia = new Entrada();
         } else{ 
         return instancia;
       }
     }
     
     
    public Entrada() {
    }

	
    public Entrada(Empenho empenho, Date data, float valorTotal) {
        
        this.empenho = empenho;
        this.data = data;
        this.valorTotal = valorTotal;
    }
    public Entrada(Empenho empenho, String numeroNota, Date data, float valorTotal) {
      
       this.empenho = empenho;
       this.numeroNota = numeroNota;
       this.data = data;
       this.valorTotal = valorTotal;
       
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
       public Empenho getEmpenho() {
        return this.empenho;
    }
    
    public void setEmpenho(Empenho empenho) {
        this.empenho = empenho;
    }
    public String getNumeroNota() {
        return this.numeroNota;
    }
    
    public void setNumeroNota(String numeroNota) {
        this.numeroNota = numeroNota;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public float getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(float valorTotal) {
        this.valorTotal = valorTotal;
    }


}


