package model;
// Generated 22/09/2013 15:07:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private Long id;
     private String complemento;
     private String bairro;
     private String numero;
     private String nome;
     private String cep;
     private String cidade;
     private String telefone;
     private String rua;
     private String cnpj;
     private String estado;
     private String contato;
     private Set empenhos = new HashSet(0);

    public Fornecedor() {
    }

	
    public Fornecedor(String nome, String telefone, String cnpj, String contato) {
        this.nome = nome;
        this.telefone = telefone;
        this.cnpj = cnpj;
        this.contato = contato;
    }
    public Fornecedor(String complemento, String bairro, String numero, String nome, String cep, String cidade, String telefone, String rua, String cnpj, String estado, String contato, Set empenhos) {
       this.complemento = complemento;
       this.bairro = bairro;
       this.numero = numero;
       this.nome = nome;
       this.cep = cep;
       this.cidade = cidade;
       this.telefone = telefone;
       this.rua = rua;
       this.cnpj = cnpj;
       this.estado = estado;
       this.contato = contato;
       this.empenhos = empenhos;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getContato() {
        return this.contato;
    }
    
    public void setContato(String contato) {
        this.contato = contato;
    }
    public Set getEmpenhos() {
        return this.empenhos;
    }
    
    public void setEmpenhos(Set empenhos) {
        this.empenhos = empenhos;
    }




}


