package model;
// Generated 22/09/2013 15:07:10 by Hibernate Tools 3.2.1.GA



/**
 * ItensSaida generated by hbm2java
 */
public class ItensSaida  implements java.io.Serializable {


     private Long id;
     private Saida saida;
     private Produto produto;
     private int quantidade;
     static ItensSaida instancia = null;   
   
     
     public static ItensSaida getInstacia(){
       if(  instancia == null){
         return instancia = new ItensSaida();
         } else{ 
         return instancia;
       }
     }
    public ItensSaida() {
    }

    public ItensSaida(Saida saida, Produto produto, int quantidade) {
       this.saida = saida;
       this.produto = produto;
       this.quantidade = quantidade;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Saida getSaida() {
        return this.saida;
    }
    
    public void setSaida(Saida saida) {
        this.saida = saida;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }




}


