package model;
// Generated 22/09/2013 15:07:10 by Hibernate Tools 3.2.1.GA



/**
 * ItensEntrada generated by hbm2java
 */
public class ItensEntrada  implements java.io.Serializable {


     private Long id;
     private Entrada entrada;
     private Produto produto;
     private float valor;
     private int quantidade;
     static ItensEntrada instancia = null;   
   
     
     public static ItensEntrada getInstacia(){
       if(  instancia == null){
         return instancia = new ItensEntrada();
         } else{ 
         return instancia;
       }
     }
    public ItensEntrada() {
    }

    public ItensEntrada(Entrada entrada, Produto produto, float valor, int quantidade) {
       this.entrada = entrada;
       this.produto = produto;
       this.valor = valor;
       this.quantidade = quantidade;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Entrada getEntrada() {
        return this.entrada;
    }
    
    public void setEntrada(Entrada entrada) {
        this.entrada = entrada;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }




}


