package model;
// Generated 22/09/2013 15:07:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Montadora generated by hbm2java
 */
public class Montadora  implements java.io.Serializable {


     private Long id;
     private String nome;
     static Montadora instancia = null;   
   
     
     public static Montadora getInstacia(){
       if(  instancia == null){
         return instancia = new Montadora();
         } else{ 
         return instancia;
       }
     }
    public Montadora() {
    }

	
    public Montadora(String nome) {
        this.nome = nome;
    }
    
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
   
}


