package model;
// Generated 22/09/2013 15:07:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdemDeServico generated by hbm2java
 */
public class OrdemDeServico  implements java.io.Serializable {


     private Long id;
     private Date dataSaida;
     private String ebPlaca;
     private Date dataEntrada;
     private String observacoes;
     private String viatura;
     private String om;
     private Set saidas = new HashSet(0);
     static OrdemDeServico instancia = null;   
   
     
     public static OrdemDeServico getInstacia(){
       if(  instancia == null){
         return instancia = new OrdemDeServico();
         } else{ 
         return instancia;
       }
     }
    public OrdemDeServico() {
    }

	
    public OrdemDeServico(Date dataSaida, String ebPlaca, Date dataEntrada, String viatura, String om) {
        this.dataSaida = dataSaida;
        this.ebPlaca = ebPlaca;
        this.dataEntrada = dataEntrada;
        this.viatura = viatura;
        this.om = om;
    }
    public OrdemDeServico(Date dataSaida, String ebPlaca, Date dataEntrada, String observacoes, String viatura, String om, Set saidas) {
       this.dataSaida = dataSaida;
       this.ebPlaca = ebPlaca;
       this.dataEntrada = dataEntrada;
       this.observacoes = observacoes;
       this.viatura = viatura;
       this.om = om;
       this.saidas = saidas;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Date getDataSaida() {
        return this.dataSaida;
    }
    
    public void setDataSaida(Date dataSaida) {
        this.dataSaida = dataSaida;
    }
    public String getEbPlaca() {
        return this.ebPlaca;
    }
    
    public void setEbPlaca(String ebPlaca) {
        this.ebPlaca = ebPlaca;
    }
    public Date getDataEntrada() {
        return this.dataEntrada;
    }
    
    public void setDataEntrada(Date dataEntrada) {
        this.dataEntrada = dataEntrada;
    }
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
    public String getViatura() {
        return this.viatura;
    }
    
    public void setViatura(String viatura) {
        this.viatura = viatura;
    }
    public String getOm() {
        return this.om;
    }
    
    public void setOm(String om) {
        this.om = om;
    }
    public Set getSaidas() {
        return this.saidas;
    }
    
    public void setSaidas(Set saidas) {
        this.saidas = saidas;
    }




}


