package model;
// Generated 22/09/2013 15:07:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Long id;
     private Montadora montadora;
     private String numeroPeca;
     private String descricao;
     private String localizacao;
     private int quantidade;
     private float valor;
     private Set itensEntradas = new HashSet(0);
     private Set itensSaidas = new HashSet(0);
     static Produto instancia = null;   
   
     
     public static Produto getInstacia(){
       if(  instancia == null){
         return instancia = new Produto();
         } else{ 
         return instancia;
       }
     }
    public Produto() {
    }

	
    public Produto(Montadora montadora, String numeroPeca, String descricao, String localizacao, int quantidade, float valor) {
        this.montadora = montadora;
        this.numeroPeca = numeroPeca;
        this.descricao = descricao;
        this.localizacao = localizacao;
        this.quantidade = quantidade;
        this.valor = valor;
    }
    public Produto(Montadora montadora, String numeroPeca, String descricao, String localizacao, int quantidade, float valor, Set itensEntradas, Set itensSaidas) {
       this.montadora = montadora;
       this.numeroPeca = numeroPeca;
       this.descricao = descricao;
       this.localizacao = localizacao;
       this.quantidade = quantidade;
       this.valor = valor;
       this.itensEntradas = itensEntradas;
       this.itensSaidas = itensSaidas;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Montadora getMontadora() {
        return this.montadora;
    }
    
    public void setMontadora(Montadora montadora) {
        this.montadora = montadora;
    }
    public String getNumeroPeca() {
        return this.numeroPeca;
    }
    
    public void setNumeroPeca(String numeroPeca) {
        this.numeroPeca = numeroPeca;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getLocalizacao() {
        return this.localizacao;
    }
    
    public void setLocalizacao(String localizacao) {
        this.localizacao = localizacao;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }
    public Set getItensEntradas() {
        return this.itensEntradas;
    }
    
    public void setItensEntradas(Set itensEntradas) {
        this.itensEntradas = itensEntradas;
    }
    public Set getItensSaidas() {
        return this.itensSaidas;
    }
    
    public void setItensSaidas(Set itensSaidas) {
        this.itensSaidas = itensSaidas;
    }




}


