package model;
// Generated 22/09/2013 15:07:10 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Long id;
     private String login;
     private String nomeCompleto;
     private String senha;
     private String perfil;
     private String posto;
     private String nomeGuerra;
     private Set saidas = new HashSet(0);
     private Set entradas = new HashSet(0);
     static Usuario instancia = null;   
   
     
     public static Usuario getInstacia(){
       if(  instancia == null){
         return instancia = new Usuario();
         } else{ 
         return instancia;
       }
     }
    public Usuario() {
    }

	
    public Usuario(String login, String nomeCompleto, String senha, String perfil, String posto, String nomeGuerra) {
        this.login = login;
        this.nomeCompleto = nomeCompleto;
        this.senha = senha;
        this.perfil = perfil;
        this.posto = posto;
        this.nomeGuerra = nomeGuerra;
    }
    public Usuario(String login, String nomeCompleto, String senha, String perfil, String posto, String nomeGuerra, Set saidas, Set entradas) {
       this.login = login;
       this.nomeCompleto = nomeCompleto;
       this.senha = senha;
       this.perfil = perfil;
       this.posto = posto;
       this.nomeGuerra = nomeGuerra;
       this.saidas = saidas;
       this.entradas = entradas;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getNomeCompleto() {
        return this.nomeCompleto;
    }
    
    public void setNomeCompleto(String nomeCompleto) {
        this.nomeCompleto = nomeCompleto;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public String getPosto() {
        return this.posto;
    }
    
    public void setPosto(String posto) {
        this.posto = posto;
    }
    public String getNomeGuerra() {
        return this.nomeGuerra;
    }
    
    public void setNomeGuerra(String nomeGuerra) {
        this.nomeGuerra = nomeGuerra;
    }
    public Set getSaidas() {
        return this.saidas;
    }
    
    public void setSaidas(Set saidas) {
        this.saidas = saidas;
    }
    public Set getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set entradas) {
        this.entradas = entradas;
    }




}


